### ISSUE TITLE
Problemi di genere :)

### ISSUE THREAD

**Issue by rjalexa** [Max1234-Ita/Liste#1]
Ciao e grazie per la risorsa che condividi.

Sarei curioso di sapere quali algoritmi hai applicato per discriminare il genere dei nomi.

Ti segnalo che Andrea appare solo nella tua lista F e non nella lista M e come saprai questo nome possono portarlo entrambi i generi e anzi è sicuramente più frequente nei maschi.

Buona giornata

**Comment by Max1234-Ita** [comment]
Ho aggiornato in locale, a breve manderò la push (domani, probabilmente).

Per separare i nomi ho usato un procedimento semiautomatico:
 - per prima cosa ho fatto una copia della lista completa e l'ho scorsa manualmente (eh sì, ho molta pazienza...), eliminando tutti i nomi maschili e lasciando solo quelli femminili, 
 - poi ho salvato la lista risultante (la F) e ho lanciato un piccolo script in Python che ha confrontato quella completa con la F: se un elemento della lista completa non era già nella F, finiva nella M... che è nata così.

Motivo per cui ci possono essere nomi nella lista sbagliata: un caso è proprio questo, di nomi che sono sia maschili che femminili, e un altro, di nomi che per sbaglio ho cancellato dalla lista F... o ho lasciato lì., come ad esempio _Leone_ e _Leonida_... che ho visto solo ora e sistemerò domani :-)

Insomma le liste sono ben lontane dalla perfezione... ma un po' alla volta si sistema tutto.

Ciao e grazie per la segnalazione!

**Comment by rjalexa** [comment]
Max santo subito :) Grazie

**Comment by Max1234-Ita** [comment]
> Max santo subito :) Grazie

Push inviata poco fa :-)
