### ISSUE TITLE
Nomi doppi da dividere

### ISSUE THREAD

**Issue by rjalexa** [Max1234-Ita/Liste#2]
Dando una occhiata alla tua ultima push, ho notato (nel file M) che ci sono nomi, specie stranieri, con due (o più) termini separati da spazio.

A mio avviso se c'è uno spazio vanno ricondotti alle singole componenti. Per esempio Adolfo Pietro dovrebbe generare un Adolfo ed un Pietro, ANDRES GREGORIO un ANDRES ed un GREGORIO. Idem per le donne. Nel mio lavoro ho dovuto gestire una ANNE MARIE (con lo spazio) e l'ho divisa in una ANNE ed una MARIE. Chiaramente se fosse scritta Annemarie sarebbe un nome solo.

My 2 cents.

Ciao e grazie.

**Comment by Max1234-Ita** [comment]
> Dando una occhiata alla tua ultima push, ho notato (nel file M) che ci sono nomi, specie stranieri, con due (o più) termini separati da spazio.
> 
> A mio avviso se c'è uno spazio vanno ricondotti alle singole componenti. Per esempio Adolfo Pietro dovrebbe generare un Adolfo ed un Pietro, ANDRES GREGORIO un ANDRES ed un GREGORIO. Idem per le donne. Nel mio lavoro ho dovuto gestire una ANNE MARIE (con lo spazio) e l'ho divisa in una ANNE ed una MARIE. Chiaramente se fosse scritta Annemarie sarebbe un nome solo.
> 
> My 2 cents.
> 
> Ciao e grazie.

In effetti hai ragione, evidentemente una delle liste che ho importato conteneva dei nomi doppi.

Non gli ho dato peso perchè per il lavoro che dovevo fare (generare identità di persone fittizie per un test), poco mi importava se qualcuno aveva il nome doppio. Però in effetti ci sta che la lista contenga nomi singoli.

Potrei aggiungere 2 righe di codice e la prossima volta che faccio girare il programma quei nomi sarebbero automaticamente splittati, ma il rischio è di avere ulteriori problemi di genere... 
Mi sa che un'altra scorsa manuale alle liste non me la toglie nessuno :-p

PS.
Meno male che posso ricercare i caratteri "spazio" nella lista!

**Comment by rjalexa** [comment]
Amico mio ma conosci la libreria "faker" di python? Ti permette di generare nomi, indirizzi etc etc etc etc plausibili ma inventati.

Per esempio per il tuo uso guarda https://faker.readthedocs.io/en/master/providers/faker.providers.person.html
a cui puoi chiedere di generare nomi, cognomi etc anche con attributo di genere.

In particolare se ti servono nomi "italiani" guarda https://faker.readthedocs.io/en/master/locales/it_IT.html#faker.providers.person.it_IT.Provider e poiù in generale il generatore "italiano" https://faker.readthedocs.io/en/master/locales/it_IT.html#

**Comment by Max1234-Ita** [comment]
Fossero solo nome e cognome, il problema!
Oltre a quello devo generare anche codice fiscale, partita IVA e IBAN... ma per fortuna anche per quello ci sono librerie Python :-) (per IBAN ne ho vista una ma non ci ho ancora provato)

**Comment by rjalexa** [comment]
Faker -> generi nomi, data e comune di nascita
CF -> https://pypi.org/project/python-codicefiscale/
P.IVA -> Faker -> https://faker.readthedocs.io/en/master/locales/it_IT.html
IBAN -> Faker -> https://faker.readthedocs.io/en/master/providers/faker.providers.bank.html

**Comment by Max1234-Ita** [comment]
Ho pushato ora i file corretti
