### ISSUE TITLE
Nome Enrico nel file femminile

### ISSUE THREAD

**Issue by matteocampiotti** [Max1234-Ita/Liste#3]
Ho notato che i nomi Enrico, Ezechiele ed Eustachio sono presenti nel file femminile e non in quello maschile

**Comment by Max1234-Ita** [comment]
Ciao, grazie per la segnalazione!
Ho già a aggiornato in locale, sarà disponibile con la prossima push.

**Comment by Max1234-Ita** [comment]
Ho pushato ora i file aggiornati
